# ====================
# APLICACI�N BASE
# ====================
spring.application.name=galtek-one-backend

# Perfil por defecto (lo cambias con SPRING_PROFILES_ACTIVE en EB o en tu IDE)
spring.profiles.active=desktop

# ====================
# LOGGING BASE
# ====================
logging.level.com.galtekone=INFO
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN

# ====================
# JPA / HIBERNATE BASE
# ====================
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# ====================
# ACTUATOR BASE
# ====================
# Solo los endpoints m�s comunes, cada perfil puede extenderlos
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized