export const API_BASE_URL = process.env.REACT_APP_API_BASE_URL || "";

export const endpoints = {
  authPublicKey: `${API_BASE_URL}/auth/keys/public`,
  authLogin: `${API_BASE_URL}/auth/login`,
  authLogout: `${API_BASE_URL}/auth/logout`,

  deviceIdentity: `${API_BASE_URL}/device/identity`,
  deviceActivate: `${API_BASE_URL}/device/activate`,

  ventasProductos: `${API_BASE_URL}/productos`,
  ventasCategorias: `${API_BASE_URL}/productos/categoria`,
  categorias: `${API_BASE_URL}/categorias`,
  ventas: `${API_BASE_URL}/ventas`,
  compras: `${API_BASE_URL}/compras`,
  compraDetalle: `${API_BASE_URL}/compraDetalle`,
  reporteGanancias: `${API_BASE_URL}/reportes-financieros/ganancias`,
  ticket: `${API_BASE_URL}/ticket/imprimir`,
  ticketPrinters: `${API_BASE_URL}/ticket/impresoras`,
  ticketConfig: `${API_BASE_URL}/configuracion/ticket`,
  ticketConfigRestore: `${API_BASE_URL}/configuracion/ticket/restaurar-base`,
  clientes: `${API_BASE_URL}/clientes`,
  metodoPago: `${API_BASE_URL}/metodoPago`,

  usuarios: `${API_BASE_URL}/usuarios`,
  usuariosOverrides: `${API_BASE_URL}/usuarios/overrides`,
  usuariosPorRol: `${API_BASE_URL}/usuarios/rol`,
  usuariosPermisos: `${API_BASE_URL}/usuarioPermisos`,
  roles: `${API_BASE_URL}/roles`,
  rolesPermisos: `${API_BASE_URL}/roles/permisos`,
  permisos: `${API_BASE_URL}/permisos`,
  empresas: `${API_BASE_URL}/empresas`,
  empresaActual: `${API_BASE_URL}/empresas/actual`,

  inventario: `${API_BASE_URL}/inventario`,
  proveedores: `${API_BASE_URL}/proveedores`,
  proveedorProducto: `${API_BASE_URL}/proveedorProducto`,
  estadoStock: `${API_BASE_URL}/estadoStock`,
  productoEstadoStock: `${API_BASE_URL}/productoEstadoStock`,
  configurarUmbrales: `${API_BASE_URL}/productoEstadoStock/configurar`,
  almacen: `${API_BASE_URL}/almacen`,
  lotes: `${API_BASE_URL}/lotes`,
  unidades: `${API_BASE_URL}/unidades`,
  entradasSalidas: `${API_BASE_URL}/entradasSalidas`,
};
