package com.galtekone.entity;

public enum CajaRelevoStatus {
    PENDING_OUTGOING_COUNT,
    PENDING_INCOMING_AUTHENTICATION,
    PENDING_INCOMING_COUNT,
    RECOUNT_REQUIRED,
    PENDING_FINAL_ACCEPTANCE,
    ACCEPTED,
    ACCEPTED_WITH_DISCREPANCY,
    PENDING_OWNER_REVIEW,
    SUPERVISOR_REVIEW,
    COMPLETED,
    CANCELLED
}
